name: 'Getting WARP+ Traffic'

on:
  workflow_dispatch:
  push:
    branches:
     - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  auto_getting_traffic:
    runs-on: self-hosted
    steps:
      - name: 'Checking'
        uses: actions/checkout@v2

  
      

      - name: 'Getting WARP+ Traffic'
        env:
          DEVICEID: ${{ secrets.DEVICEID }}      
        run: python warp.py
